version: '3'

services:
  database:
    image: postgres:latest

    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}

    container_name: database

    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: always
    command: ["postgres", "-c", "log_statement=all"]

  backend:
    build: .
    container_name: thread
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:


      