# Generated by Django 4.2.4 on 2023-08-30 11:59

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_alter_thread_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='video',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='', validators=[cloudinary_storage.validators.validate_video], verbose_name='Видео'),
        ),
    ]
