# Generated by Django 4.2.4 on 2023-09-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_alter_thread_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quote or repost', 'verbose_name_plural': 'Quotes and reposts'},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='repost',
        ),
        migrations.AddField(
            model_name='quote',
            name='is_repost',
            field=models.BooleanField(default=True, verbose_name='Репост или цитата'),
        ),
        migrations.AddField(
            model_name='thread',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Comment'),
        ),
    ]
