# Generated by Django 4.2.4 on 2023-09-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_alter_quote_options_remove_thread_repost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='addional_text',
            new_name='additional_text',
        ),
    ]
