# Generated by Django 4.2.4 on 2023-09-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_alter_thread_options_remove_thread_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='threads.thread', verbose_name='Thread'),
        ),
    ]
