# Generated by Django 4.2.4 on 2023-09-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_alter_video_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Thread'),
        ),
    ]
