# Generated by Django 4.2.4 on 2023-10-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.URLField(),
        ),
    ]
