# Generated by Django 4.2.4 on 2023-08-23 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_follower_follower_unique_followers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follower',
            name='unique_followers',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='followers',
        ),
        migrations.AddField(
            model_name='follower',
            name='follows',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL, verbose_name='To follow'),
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL, verbose_name='Who follow'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='pending_request',
            field=models.BooleanField(default=True, verbose_name='Follow request'),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('user', 'follows'), name='unique_followers'),
        ),
    ]
