# Generated by Django 4.2.4 on 2023-08-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofile_bio_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_following',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Following'),
        ),
    ]
