# Generated by Django 4.2.4 on 2023-08-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_number_of_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Private'),
        ),
    ]
