# Generated by Django 4.2.4 on 2023-09-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userprofile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Surname'),
        ),
    ]
